# Generated by Django 6.0.3 on 2026-03-25 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bilty_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('material_name', models.CharField(max_length=100)),
                ('origin', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('distance_km', models.PositiveIntegerField()),
                ('weight_tonnes', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate_per_tonne', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_freight', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('is_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.driver')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.vehicle')),
            ],
        ),
    ]
