# Generated by Django 6.0.3 on 2026-03-26 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='booking_type',
            field=models.CharField(choices=[('pickup', 'Company Pickup'), ('drop', 'Customer Drop at Transport')], default='drop', max_length=20),
        ),
        migrations.AddField(
            model_name='shipment',
            name='delivery_type',
            field=models.CharField(choices=[('door', 'Door Delivery'), ('office', 'Office Collection')], default='office', max_length=20),
        ),
        migrations.AddField(
            model_name='shipment',
            name='purchase_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
