# Generated by Django 6.0.3 on 2026-03-26 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0002_shipment_booking_type_shipment_delivery_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='distance_km',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
