# Generated by Django 6.0.3 on 2026-03-26 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0004_shipment_diesel_expenses_shipment_driver_allowance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='net_profit',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='diesel_expenses',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='driver_allowance',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='other_expenses',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='purchase_cost',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='rate_per_tonne',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='toll_expenses',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='total_freight',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='weight_tonnes',
            field=models.FloatField(default=0),
        ),
    ]
