# Generated by Django 6.0.3 on 2026-03-26 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0005_shipment_net_profit_alter_shipment_diesel_expenses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='consignee_name',
            field=models.CharField(default='Unknown', max_length=200, verbose_name='Receiver Company'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='consignor_name',
            field=models.CharField(default='Unknown', max_length=200, verbose_name='Sender Company'),
        ),
    ]
